---
title: "Iteration and list columns"
author: "Daniel Ojeranti"
date: "11/8/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
set.seed(1)
```


## Lists

You can put anything in a list

```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_char = c("My", "name", "is", "Jeff"),
  vec_logical = c(TRUE, TRUE, TRUE, FALSE),
  summary     = summary(rnorm(1000))
)

l$vec_numeric
l[[1]]
l[[1]][1:3]

```

## For loop

Create list

```{r}
list.norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(40, 0, 5),
    c = rnorm(30, 10, .2),
    d = rnorm(20, -3, 1)
  )

```

Old function

```{r}
mean.and.sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } 
  
  else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

Apply function to lists

```{r}
mean.and.sd(list.norms[[1]])
mean.and.sd(list.norms[[2]])
mean.and.sd(list.norms[[3]])
mean.and.sd(list.norms[[4]])
```

Lets use a for loop:

```{r}

# We want output[[1]] = mean.and.sd(list.norms[[1]])

output = vector("list", length = 4)

for (i in 1:4 ){
  
output[[i]] = mean.and.sd(list.norms[[i]])

}

```

## Trying map 

```{r}
output = map(list.norms, mean.and.sd)
```

What if I want a different function...?

```{r}
output =  map(list.norms, IQR)
```

## Different types of maps

```{r}
output =  map_dbl(list.norms, IQR)

output =  map_df(list.norms, mean.and.sd, .id = "input")
```

## List columns

```{r}
list.norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(40, 0, 5),
    c = rnorm(30, 10, .2),
    d = rnorm(20, -3, 1)
  )

listcol.df =
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list.norms
  )

listcol.df %>% pull(name)
listcol.df %>% pull(samp)

listcol.df$samp[[1]] # First element from my list column


mean.and.sd(listcol.df$samp[[1]]) #A pplying the function to first element

```

# Maping

```{r}
map(listcol.df$samp, mean.and.sd)


listcol.df = 
  listcol.df %>% 
  mutate(summary = map(samp, mean.and.sd))

listcol.df
```

## Weather Data

```{r}

weather.df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```

Get our list columns...

```{r}
weather.nest =
  weather.df %>% 
  nest(data = date:tmin)

weather.nest %>% pull(name)
weather.nest %>% pull(data)

weather.nest$data[[3]]
```

Want to regress tmax on tmin for each station.

```{r}
lm( tmax ~ tmin, data = weather.nest$data[[1]])

# Writing a function to do the regression

weather.lm = function(df){
  
lm( tmax ~ tmin, data = df)

  }

weather.lm(weather.nest$data[[1]])


output = vector("list", 3)

for (i in 1:3){
  
  output[[i]] = weather.lm(weather.nest$data[[i]])
}

```


```{r}
#Transition in a map

map(weather.nest$data, weather.lm)

# What about a map in a list column

weather.nest %>% 
  mutate(models = map(data,weather.lm))
```

