---
title: "writing functions"
author: "Daniel Ojeranti"
date: "11/7/2020"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
```

# Somthing simple

```{r}
set.seed(1)

x.vec = rnorm(25, mean = 5, sd = 3)

(x.vec - mean(x.vec)) / sd(x.vec)

```

 Want a function to compute z scores

```{r}
z.scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  z
}

z.scores(x.vec)
```

Trying function on other things

```{r,error=TRUE}
z.scores(3)
z.scores("Mehoy Nehoy")
z.scores(mtcars)
z.scores(c(TRUE ,TRUE ,FALSE ,TRUE))

```

update function

```{r}

z.scores = function(x) {
  
  if (!is.numeric(x)){
    stop("Input must be numeric")
  }
  

  if (length(x) < 3){
    stop("Input must have at least 3 numbers")
  }
  z = (x - mean(x)) / sd(x)
  z
}


```

 These should give errors
 
```{r, error=TRUE}
z.scores(3)
z.scores("Mehoy Nehoy")
z.scores(mtcars)
z.scores(c(TRUE ,TRUE ,FALSE ,TRUE))

```

# Multiple outputs

```{r}

mean.and.Sd = function(x) {
  
  if (!is.numeric(x)){
    stop("Input must be numeric")
  }

  if (length(x) < 3){
    stop("Input must have at least 3 numbers")
  }
  
mean.x = mean(x)
sd.x = sd(x)

tibble(
  mean = mean.x,
  sd = sd.x
)

}
```

Check that function works

```{r}
x.vec = rnorm(100, mean = 3, sd = 5)
mean.and.Sd(x.vec)

```

# Multiple Inputs

I'd like to do this with a function

```{r}
sim.data =
  tibble(
    x = rnorm(n = 100, mean = 4, sd = 3)
  )

sim.data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
)
```


```{r}
sim.mean.sd = function(n, mu, sigma) {
  
# Generates a data frame that follows the n,mu, sigma from the function command
  
  sim.data =
  tibble(
    x = rnorm(n = n, mean = mu, sd = sigma)
  )

# Takes the information from the tibble and summarizes(outputs) the mean an standard deviation from it.

sim.data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
)
  
}

sim.mean.sd(100,6,3)

```

